# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
ENV['SWIFT_VERSION'] = '5'

target 'RCTVideo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RCTVideo

end

target 'RCTVideo-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RCTVideo-tvOS

end
